[project]
name = "cian"
version = "0.1.0"
description = "Add your description here"
requires-python = ">3.11,3.13"
dependencies = [
    "playwright>=1.52.0",
    "pymongo>=4.13.0",
    "requests>=2.32.3",
]
